---
title: Next Generation Planning - Structuring and Sharing Drivers of Ecosystem Change Data for the St. Lawrence
author: David Beauchesne^1^, Rémi Daigle^2^, Steve Vissault^3^, Dominique Gravel^3^, Andréane Bastien^4^, Simon Bélanger^1^, Pascal Bernatchez^1^, Clément Chion^5^, Peter S. Galbraith^6^, Benjamin Halpern^7^, Camille Lavoie^2^, Christopher W. McKindsey^6^, Michel Starr^6^, Anne-Sophie Ste-Marie^4^, Philippe Archambault^2^
date: 2018-09-19
fontsize: 12pt
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    fig_width: 3
  pdf_document:
    toc: false
  word_document:
    toc: false
header-includes:
   - \usepackage{lineno}
   - \linenumbers
relativeurls: true
bibliography: platformMS.bib
csl: frontiers.csl
link-citations: yes
---

<!--
setwd('/users/davidbeauchesne/dropbox/phd/phd_obj1/stressor_spat_dist/platformMS/')
rmarkdown::render('./platformMS.rmd', 'html_document')
rmarkdown::render('./platformMS.rmd', 'pdf_document')
rmarkdown::render('./platformMS.rmd', 'word_document')
-->

^1^Université du Québec à Rimouski \newline
^2^Université Laval \newline
^3^Université de Sherbrooke \newline
^4^St. Lawrence Global Observatory \newline
^5^Université du Québec en Outaouais \newline
^6^Department of Fisheries and Oceans Canada \newline
^7^University of California \newline

# Abstract

Gathering data for large scale, systematic research initiatives such as regional
multi-driver analyses can be a very challenging - not to say painful - process.
On one hand, there is an overwhelming wealth of data available, while on the
other hand, some important data remain largely unavailable or inaccessible.
Coupled with political intricacies, such as the multi-jurisdictional division
of the St. Lawrence system, the data gathering process can quickly become
intractable. To address this issue in the context of ecosystem based management,
we launched an open data platform focused on the spatial distribution and
intensity of drivers in the St. Lawrence. The objective of this platform is to
initiate a community project based on transparency, inclusivity and adaptiveness,
and to promote existing environmental monitoring programs while identifying key
knowledge gaps. We believe that this initiative is urgently needed for the
benefit of both scientific research and ecosystem based management initiatives
within the St. Lawrence.

# Context

With awareness of human impacts on the oceans increasing globally, there has
been a growing demand for systematic and large scale environmental management
schemes, such as ecosystem-based management, systematic conservation planning,
and strategic environmental assessment [@margules2000; @jones2016]. Beyond
substantial political and scientific commitment, such initiatives require the
proper infrastructures and tools allowing for efficient data reporting and
adaptive, continuous monitoring, all of which hinge on the construction of
large, holistic datasets.

Gathering data for large scale, systematic initiatives can however be a very
challenging - not to say painful - process. On one hand, there is an
overwhelming and expanding wealth of data available at our fingertips. On the
other hand, crucial data are lacking and remain largely unavailable or
inaccessible for a variety of reasons, including proprietary rights and
unwillingness to share. Both are fraught with pitfalls. Information overload
can lead to decreased decision-making ability, financial losses, delayed
decisions, massive effort duplication, disproportionate appropriation of
research funds, and it may obscure knowledge gaps amid a sea of information
[@oreilly1980]. The impacts of a lack of information are self-evident: without
knowledge, appropriate decision-making is beyond our grasp. Coupled with
political intricacies, such as multi-jurisdictional management, the data
gathering process can quickly become intractable.

There are now multiple initiatives that partly address this issue by assembling,
organizing and sharing vast arrays of relevant data. Biotic data can be accessed
through web portals such as the Ocean Biogeographic Information System
[OBIS; @obis2018], the Global Biodiversity Information Facility
[GBIF; @gbif2018], the Global Biotic Interactions platform [GloBI; @poelen2014],
and the World Register of Marine Species [WoRMS; @worms2017]. Abiotic data can
similarly be accessed through WorldClim [@hijmans2005], Bio-ORACLE
[@tyberghein2012], and MARSPEC [@sbrocco2013]. There are also global initiatives
such as the Group on Earth Observations Biodiversity Observation Network
[GEO BON; @scholes2012] and the Census of Marine Life [CoML; @coml2010] which
are focused on organizing, coordinating and acquiring essential ecological
parameters to support decision-making and management.

Drivers of ecosystem change are conspicuously missing from this list
[but see @halpern2015], even though data describing their distribution and
intensity at a resolution informative to decision-making and scientific research
are crucial to large-scale environmental management. For this paper, we define
drivers of ecosystem change (hereafter referred to as drivers) as any process
that may disturb a system beyond natural thresholds. Drivers may be
natural (*e.g.* sea surface temperature anomalies and hypoxia) or anthropogenic
(*e.g.* fisheries and marine pollution) in origin.

To address this issue, we are launching an open data platform focused on the
description of the spatial distribution and intensity of drivers in the Estuary
and Gulf of St. Lawrence in Canada, a unique and complex social-ecological
system. The overarching goal of this platform is to initiate a community-led
project based on transparency, inclusivity and adaptiveness that will increase
accessibility to critical data for scientific inquiries and decision-making.
We also wish to use this platform to promote pre-existing environmental
monitoring initiatives and identify key knowledge gaps. The objective of this
paper is to present the initiative, the guiding principles underlying its
inception, and its potential applications and benefits. Most importantly, we
wish to initiate a call for collaboration to any person, group or organization
who might be interested in contributing to this initiative.

<br/>

# The St. Lawrence System

The St. Lawrence, formed by one of the largest estuaries in North America and a
vast interior sea, is an ecologically complex system characterized by highly
variable environmental conditions and oceanographic processes, both in space
and time [@el-sabh1990; @white1997; @dufour2007]. It thus offers a unique and
heterogeneous array of habitats suited for the establishment of diverse and
productive ecological communities [@savenkoff2000]. It concomitantly provides
a wealth of ecosystem services that have historically and contemporarily
benefited the Canadian economy. It holds a rich fisheries industry targeting
over 50 species, serves as the gateway to eastern North-America by granting
access to more than 40 ports, has a booming tourism industry and an expanding
aquaculture production, develops emerging activities and a yet untapped
hydrocarbon potential [@beauchesne2016]. With major investments recently made
and more forthcoming in economic and infrastructure development and research
[*e.g.* @goq2015; @rqm2018], an intensification of the human footprint is
expected in the St. Lawrence.

Arising from this expected intensification and the experience of past and
current ecological tragedies [*e.g.* the collapse of cod fisheries and the
decline of the beluga population; @frank2005; @plourde2014; @dempsey2018] is a
call for an integrative and holistic approach to managing the St. Lawrence as a
whole. Yet jurisdiction over the St. Lawrence is divided between the Canadian
federal government and five provincial governments, *i.e.* Newfoundland and
Labrador, New Brunswick, Nova Scotia, Prince Edward Island, and Québec, with
each governmental entity further divided into multiple departments, each with
different mandates. Researchers from dozens of academic institutions and
countless local organizations also share an interest in the St. Lawrence.
This results in highly scattered expertises and heterogeneous data management
and sharing processes, which we wish to address through this open data platform
initiative.

# Open Data Platform

## Guiding principles

In accordance to the overarching goals of the platform, which is to establish a
transparent, inclusive and adaptive community-led project, to promote pre-existing
environmental monitoring initiatives and identify knowledge gaps, we propose
four foundational guiding principles:

- Create a unifying and inclusive project
- Foster open, transparent and replicable science
- Embrace adaptiveness as a core principle
- Adhere to the principles of scientific peer-review

### Unity and inclusiveness

**How**: By actively inviting, seeking, and developing collaborations as well as
encouraging constructive criticism from the inception and throughout the
lifetime of the platform.

**Why**: Operating over such large scales in time, space and subject matter
requires a vast and diverse expertise that cannot possibly be possessed by any
one individual or organization. Consequently, we are launching a crowd
science-like project [see @franzoni2014] that seeks to mobilize all entities
with relevant expertise. As such, we are inviting any individual or organization
interested in collaborating in this project to contact us.

### Openness, transparency and replicability

**How**: By striving to provide all data, metadata, methods descriptions, and
code used to generate platform content and structure.

**Why**: Open data has been propelled to the forefront of scientific research
in an era of big data science. By moving towards large scale, cross-disciplinary
research and management projects, there is a growing need to increase the
efficiency of data access, integration and analysis [@reichman2011]. Embracing
open-data accelerates research outcomes, improves transparency and replicability,
assists in discovering incorrect data and corroborating study findings, and
decreases overall costs of research initiatives
[@reichman2011; @poisot2013; @lowndes2017]. As such, many scientific journals
(*e.g.* PLoS, Nature, Science), governmental agencies [*e.g.* @goc2016] and
other institutions are increasingly adopting open data-sharing policies as
part of their mandate. Our goal is to foster open data science by creating a
fully open, transparent and replicable open data platform.

### Adaptiveness

**How**: By setting up mechanisms allowing for cyclic reviews of platform
content and for the integration of new material (*e.g.* data and methods) as it
becomes available or accessible.

**Why**: In the face of uncertainty and in an effort to address impending
environmental changes, adaptive management has been identified as the chief
strategy to guide efficient decision-making
[*e.g.* @costanza1998; @margules2000; @keith2011; @jones2016] and has already
been discussed in the context of multi-drivers and cumulative impact assessments
[@halpern2015; @beauchesne2016; @cote2016]. Adaptive management can only be
truly achieved through a commitment to adaptive monitoring and data reporting
[@margules2000; @halpern2012; @lubchenco2015]. We further contend that adaptive
management requires the development of adaptive monitoring tools, which we seek
to address for the St. Lawrence through a continuously-evolving platform.

### Peer-review

**How**: By ensuring that platform content has been processed through a rigorous
peer-review process.

**Why**: Peer-review is a fundamental tenet of science that ensures robustness
and quality of published research and lends credibility to communicated
scientific outputs [@ware2008; @rennie2016]. In an effort to
uphold the highest standards of scientific research, we wish to provide data
layers that have been thoroughly reviewed, ideally through peer-reviewed
journals. Peer-reviewed material will thus be clearly identified on the
platform, with appropriate citations provided.

## Benefits

Arguably the most meaningful benefit emerging from operating under our guiding
principles is the collective recognition of the depth of our current
understanding of the threats to the St. Lawrence. This community-wide surge in
consciousness could pay quick dividends in scientific and management
collaborations and efficiency, data management, and environmental monitoring.

The platform will also create a significant multi-jurisdictional collaborative
capacity between regional experts and create a community-led movement under
which local and specialized initiatives may be unified under a single umbrella.
This type of crowd science can, by drawing on the knowledge and efforts of a
wide range of contributors, expand avenues of scientific inquiry, decrease
overall research costs, increase research speed, and decrease effort duplication
[@franzoni2014]. This could easily lead to new and unforeseen avenues of
research and funding for new initiatives in the St. Lawrence. Critically,
awareness of the state of our knowledge will enable the identification of key
knowledge gaps, which will assist in prioritizing and optimizing research
efforts.

The platform will also promote and consolidate existing and highly valuable
environmental initiatives already in place in the St. Lawrence. Notable examples
are the annual review of physical [@galbraith2017], chemical and biological
[@devine2017] oceanographic conditions in the St. Lawrence, the fisheries
monitoring program that provides details on a significant proportion of fishing
activities in the St. Lawrence [@dfo2016] and the annual groundfish and shrimp
multidisciplinary survey [@bourdages2017]. There is also a valuable
characterisation of benthic [@dutil2011], epipelagic (*i.e.* 0-30m surface
layer) and coastal [@dutil2012] habitats of the St. Lawrence available as well
as a portal on Canada's shoreline classification [@eccc2018]. There are also
nascent efforts to make available information on several human activities in the
St. Lawrence. For example, the Marine Spatial Data Infrastructure portal
provides data on zoning, shipping, port activities, and other human activities
in Canadian waters, including the St. Lawrence [@goc2018].

Typically, however, many such initiatives originate from local projects
and their resulting datasets are often highly fragmented in availability,
quality, and experimental approaches [@reichman2011]. The platform project
could address this issue by supporting a push towards a regional standardization
of local protocols and practices, the identification of indicators of stress
within the St. Lawrence, and the establishment of a list of Essential Driver
Variables [EDV; see @pereira2013 for a description of the equivalent Essential
Biodiversity Variables]. Additional steps towards standardization could also be
taken by emulating protocols elaborated through international programs like
GEO BON [@scholes2012] and CoML [@coml2010].

Over the long-term, cyclic updates of platform content will also provide
time-series for drivers and provide valuable insights on the temporal trends of
drivers intensity and distribution. This could provide the necessary mechanisms
to allow for adaptive monitoring and help identify early-warning signals for
looming significant ecosystem transitions [*e.g.* @boettiger2013].

Finally, major gains in data availability and accessibility, for everyone, will
constitute major breakthroughs for environmental sciences. It will effectively
end the need to reach dozens of experts across dozens of departments over
extensive periods of time in order to assemble the data needed for integrated
research. Standardized protocols will also enable the production of comparable
and robust metadata and ease the regional aggregation of local datasets
[@reichman2011].

## Content

Building the backbone of the platform allowed us to initiate collaborations,
identify relevant experts in each field, integrate data on drivers that are
already freely and readily available, and begin identifying knowledge gaps.
It also serves as the stepping stone towards the long-term community project
we are envisioning.

We first identified a list of 34 drivers (Table 1) known to potentially impact
the St. Lawrence. This list was informed by global cumulative impacts
assessments initiatives [@halpern2008; @halpern2015], regional holistic
evaluation of the state of the St. Lawrence [@dufour2007; @benoit2012], and
through communications with regional experts.

We initialized the content of the platform using data from NCEAS’s online data
repository that was built through a global cumulative impact assessment
initiative [@halpern2015b]. Available global data for drivers deemed important
in the St. Lawrence thus serve as version 1.0 of driver layers on the platform
(Table 1). While some data layers are rather uninformative at the scale of the
St. Lawrence (*e.g.* acidification), some layers provide valuable information at
a resolution adequate for use at regional scales and currently constitute the
best available knowledge for the St. Lawrence (*e.g.* marine pollution).

We then initiated the production of version 2.0 of driver layers, either for
drivers for which data are unavailable globally (*e.g.* aquaculture) or for which
alternative data constitute an upgrade over the existing global data, typically
from regional or local initiatives (*e.g.* fisheries). We have thus far updated
or characterized 12 drivers and are actively working on the characterization of
12 drivers, with their development at various stages of completion (Table 1).
We are also actively seeking collaborations or data for 10 drivers. All versions
of driver layers will remain available on the platform. The development version
allowing data visualization is currently available at webpage.

# Applications

Assembling all drivers in a single platform will provide a wide array of
visualization and analytical possibilities that can be useful for both decision
making and scientific research. Here we describe two such potential applications.

## Multi-drivers assessment

This platform initiative will enable usual, single driver impact assessments,
but it will also pave the way towards holistic assessments of the state of the
St. Lawrence by enabling the study of combinations of multiple drivers. For
instance, drivers like hypoxia (Figure \ref{fig1}A) and demersal destructive
fisheries (Figure \ref{fig1}B) are known to occur mainly in deeper areas of the
St. Lawrence. By combining them (Figure \ref{fig1}C), we can evaluate which
regions in the St. Lawrence are more likely to be affected by both drivers
simultaneously and evaluate the relative intensity at which they tend to
co-occur (Figure \ref{fig1}D). Doing this, we observe that hypoxia and bottom
fisheries tend to co-occur in the St. Lawrence and that they do so at relatively
high intensities, with extensively used fishing grounds also characterized by
low levels of oxygen neighboring the limits of hypoxia (*i.e.* ~0.7 mg*L^-1^,
corresponding to ~30% saturation).

Fisheries in the St. Lawrence have historically affected fish stocks
and habitat quality [@moritz2015]. Hypoxia, meanwhile, decreases overall
habitat quality but has variable effects that are species-dependent, ranging
from well-adapted (*e.g.* northern shrimp *Pandalus borealis* and Greenland
halibut *Reinhardtius hippoglossoides*; [@pillet2016] to reduced growth rates
[@dupont2013] and avoidance of oxygen depleted habitats
[*e.g.* Atlantic cod *Gadus morhua*; @chabot2008] to increased mortality
[*e.g.* sessile benthic invertebrates; @eby2005; @belley2010]. Certain species
may thus be negatively affected by fisheries and withstand hypoxia but still
experience a decrease in prey availability, while others may be negatively
affected by the compounded effect of both drivers. By providing data on multiple
drivers and their spatial interaction, the platform would yield valuable
insights for the integrated management of the St. Lawrence and the ability to
tackle complex problems not restricted to single drivers.

## Multi-scale management

Management is typically distributed across multiple jurisdictional, spatial and
temporal scales. For example, in the St. Lawrence, commercial fisheries are
managed at the federal level, with 3 regional jurisdictions. Ports and shipping,
meanwhile, are managed by a combination of local, provincial and federal
institutions. Such divisions, while necessary, isolate decision-making into
contextualized boxes even though decisions may have consequences reaching far
beyond its immediate context. With the appropriate time-series data provided by
cyclic updates of platform content and a commitment to adaptive monitoring, the
platform will allow us to visualize and evaluate management outcomes and
efficiency across scales and holistically. We draw on two topical issues in
the St. Lawrence and use simulated data to illustrate this.

The first issue is the case of the North Atlantic Right Whale
(NARW; *Eubalaena glacialis*), an endangered species that received a lot of media,
political and scientific attention in the summer of 2017 when 12 dead NARW and
5 live-entanglements were documented in the St. Lawrence [@daoust2017]. It was
established that the most likely causes of death were vessel collisions and
fishing activities [@daoust2017], and a series of management actions were put
in place to limit impacts to NARW [@dfo2018b; @tc2018]. One such action is a
static fixed engine fisheries closure in the Gulf of St. Lawrence in an area
encompassing 90% of 2017 NARW observations. With the platform, we can visualize
the fisheries intensity before (Figure \ref{fig2}B) and after the management
action (Figure \ref{fig2}D) to evaluate effects of management actions on fixed
engine fisheries.

The second issue is the case of port development initiatives in the
St. Lawrence. Five local port projects scattered through the St. Lawrence have
been submitted for an environmental assessment review at the Canadian
Environmental Assessment Agency [@ssl2018]. Of those project, we focus on the
marine terminal project on the north shore of the Saguenay River, for which a
draft environment assessment report was published [@ceaa2018] as well as a
science response by the Canadian Science Advisory Secretariat [@dfo2018]. It is
reported that the establishment of this port alone would lead to a 2.33-fold
increase in the number of ships in the Saguenay River by 2030, with vessels
transiting through the St. Lawrence to reach international markets
[@ceaa2018; @dfo2018]. With the platform, we can visualize shipping intensity
before (Figure \ref{fig2}C) and after (Figure \ref{fig2}E) to evaluate
the effects of this project on local marine traffic, but along the whole river
and the estuary.

Critically, the platform will allow users to explore the compounded effects of
management outcomes by providing the ability to explore effects on the
integrative distribution and intensity of drivers by considering them all
simultaneously (Figure \ref{fig2}A, F), or using any combination of drivers desired.
Similarly, the effects of multiple decision-making processes could be evaluated
in combination to see if their outcomes overlapped. This could provide an
invaluable tool for management as well as provide the tools necessary to justify
and encourage a strong commitment to adaptive monitoring.

# Ongoing development & perspectives

In this perspective paper we presented an adaptive open data platform focused on
the description and intensity of drivers of ecosystem change specifically built
for the Estuary and Gulf of St. Lawrence, Canada. The core objectives underlying
this initiative are to create a community-led project based on transparency,
inclusivity, and adaptiveness that will increase accessibility to critical data
for scientific inquiries and management schemes and help in identifying key
knowledge gaps.

With the project now officially launched, there are a number of initiatives
which we must continue to build and some that are in need of development.
Foremost on that list is to continue to foster collaborations, develop platform
content with relevant data and methods, and identify knowledge gaps. Concrete
mechanisms to adhere to all guiding principles must also be detailed, including
drafting a data sharing policy, developing standard metadata, building a fair
and efficient organizational structure, and secure funding for the long-term
integration of the platform and its guiding principles to the management of the
St. Lawrence.

Beyond what we already discussed, we also believe that the potential
applications of this platform are vast and far-reaching. It will undoubtedly
serve as critical information to broader research and management initiatives,
such as cumulative impacts assessments
[*e.g.* @halpern2008; @halpern2015; @beauchesne2016], the creation of a Canadian
Ocean Health Index [@halpern2012; @daigle2017] and the use of social-ecological
metanetworks for the management of ecosystem functions and services in the
St. Lawrence [@dee2017].

It could also be coupled with or serve as a means of operationalizing a network
of sampling stations across the St. Lawrence and provide real-time, integrated
data on drivers within the St. Lawrence to guide efficient decision-making and
monitoring [*e.g.* @onc2018]. Decision-making scenarios could also be tested
by simulating management outcomes and evaluating their influence on the
distribution and intensity of drivers in the St. Lawrence. We also expect other
unforeseen applications to emerge as the initiative gains momentum and users
begin using the content of the platform to address their own specific
objectives.

Ultimately, this platform represents a much needed solution to address important
issues in data management that could help in radically shifting environmental
impact assessment practices towards efficient, adaptive and holistic
ecosystem-based management of whole ecosystems, in the St. Lawrence and
elsewhere in the world. All it requires to be successful is for the scientific
and political communities to fully commit to open data, adaptive monitoring and,
most of all, an integrated vision of ecosystem management.

# Acknowledgements

TO WRITE

\newpage

# Tables

Table 1. List of drivers listed for inclusion in the multi-drivers platform. Their development status is detailed as such: data unavailable: no data is known to be available; seeking collaboration: we are actively seeking collaborations and expertise to develop this drivers layer; in development: we are in the process of building the driver layer, at varying levels of progress; complete: driver layer is complete for this version of the platform. Note that drivers identified as complete but identified with an * are were completed using data from [@halpern2015b] and that development of these drivers using regional data may still be pursued. Finally, a relative evaluation of progress made towards completion of each driver is presented. Black and grey boxes are for regional and global data development, respectively.

```{r table1, echo=F, fontsize=4}
readRDS('./table1.RDS')
```

\newpage

# Figures

![Figure 1. Example of platform content using the spatial distribution and the intensity of hypoxia and demersal destructive fisheries in the St. Lawrence. An index of hypoxia (**A**) was measured by normalizing values of bottom oxygen saturation percentage [@dutil2011] between 0 and 1 so that values close to 0 are fully saturated in $O_2$, while values close to 1 are hypoxic. Areas with less than 30% $O_2$ saturation (index $>$ 0.7) are generally considered hypoxic. Demersal destructive fisheries (**B**) correspond to fishing activities using trawl and dredges. Intensity of fishing activities was measured using fisheries location data collected between 2010 and 2015 [@dfo2016] and a 2km buffer to consider trawling and dredging area. For each study area cell ($1 km^2$), fishing intensity (FI) was measured as the annual area weighted total biomass ($kg$) yield for all species captured: $FI = \sum_{i = 1}^{n} B_i * \frac{Area_{Fish}}{Area_{Cell}}$, where $B_i$ is the total annual biomass captured in each cell. As fishing intensity was highly skewed towards zeroes, we FI was log transformed to obtain a workable distribution. Values were then normalized to allow comparison with hypoxia values. drivers intensity was summed (**C**) to visualize the combination of hypoxia and demersal destructive fisheries. Finally, individual density and the co-intensity of hypoxia and demersal destructive fisheries was investigated with a kernel analysis (**D**).\label{fig1}](./figure1.png)

\newpage

![Figure 2. Example of multi-scale management of the Estuary and Gulf of St. Lawrence using time-series data from the drivers platform. Regional (**B**, **C**) and local (**D**, **E**) scale decision-making are contrasted to show how management processes operating at different scales can influence (**A**, **F**). The data used for the period before management actions (**A**, **B**, **C**) is available on the platform, while the data used for the period after management actions (**D**, **E**, **F**) was simulated to correspond to their likely effects on drivers distribution and intensity. The effects of port development on shipping were simulated by increasing shipping intensity from the St. Lawrence Estuary through the Saguenay River to the projected marine terminal by the expected 2.33-fold increase in number of ships [**D**; @dfo2018]. The effects of the static fixed engine fisheries closure in the Gulf of St. Lawrence in response to North Atlantic Right Whale (*Eubalaena glacialis*) 2017 casualties were simulated by redistributing the mean total annual biomass yield from the closure area to neighbouring fishing zones (**F**). Effects of local and regional management actions were then used to update the overall distribution and intensity of all drivers in the St. Lawrence (**F**). \label{fig2}](./figure2.png)

\newpage

# Reference
